#!/usr/bin/env node
/**
 * keygen.mjs — season-0 key tool (PROJECT.md §7): generate + keystore-encrypt real EVM
 * wallets for agent zero and the first-generation designs. Keys are AES-256-GCM encrypted with
 * KEYSTORE_PASSPHRASE into data/keystore/ (gitignored); ONLY addresses are printed.
 *
 * Usage:  KEYSTORE_PASSPHRASE=… node scripts/keygen.mjs [--only <id>]
 * Backup: copy data/keystore/*.json somewhere offline; they are useless without the passphrase.
 */
import { existsSync, readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const KEYSTORE_DIR = resolve(ROOT, "data/keystore");

// pull passphrase from env or .env (never from argv — it would land in shell history)
let passphrase = process.env.KEYSTORE_PASSPHRASE;
if (!passphrase && existsSync(resolve(ROOT, ".env"))) {
  const m = readFileSync(resolve(ROOT, ".env"), "utf8").match(/^\s*KEYSTORE_PASSPHRASE\s*=\s*(.+?)\s*$/m);
  if (m) passphrase = m[1];
}
if (!passphrase) {
  console.error("KEYSTORE_PASSPHRASE not set (env or .env). Refusing to generate unencryptable keys.");
  process.exit(1);
}

const chain = await import(new URL("../packages/chain/dist/index.js", import.meta.url)).catch(() => null);
if (!chain?.birthWallet) {
  console.error("build packages/chain first (pnpm -w run typecheck emits dist).");
  process.exit(1);
}

const only = process.argv.includes("--only") ? process.argv[process.argv.indexOf("--only") + 1] : null;
// NOTE: "mother-treasury" was renamed to "operator-treasury" in B0 (2026-08-02, approved by
// Charles) — the keystore entry was migrated in place (same key, new id).
// The 8 first-generation designs were retired 2026-08-02 — only the operator treasury key is
// generated by default; agent zero's wallet is minted on demand by season0-genesis.mjs.
const ids = only ? [only] : ["operator-treasury"];

const existing = new Set(chain.listWallets(KEYSTORE_DIR).map((w) => w.id));
for (const id of ids) {
  if (existing.has(id)) {
    const addr = chain.listWallets(KEYSTORE_DIR).find((w) => w.id === id).address;
    console.log(`${id}: exists → ${addr}`);
    continue;
  }
  const addr = chain.birthWallet(KEYSTORE_DIR, id, passphrase);
  console.log(`${id}: generated → ${addr}`);
}
console.log(`\nkeystore: ${KEYSTORE_DIR} (encrypted, gitignored — back it up offline)`);
